# Cleanse the "../" directory of the following:
#     - all files with a PYC extension.
#     - all "trash files" listed below:
#         . parsetab.py - generated by the ply library.

import os


trashFiles = ('parsetab.py',)

print 'Changing to root directory...'
os.chdir('../')

print 'Scanning for garbage files...'

for root, folders, files in os.walk('.'):
    for filename in files:
        if filename.endswith('.pyc') or (filename in trashFiles):
            print "Removing '%s'..." % filename
            os.unlink(os.path.join(root, filename))

print 'Done.'
os.system('pause')
